# Generated by Django 5.0.2 on 2024-06-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_employee_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='overtime_hours',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='overtime_pay',
        ),
        migrations.AddField(
            model_name='payroll',
            name='month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
