# Generated by Django 5.0.2 on 2024-06-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_leave_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='clock_in',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='clock_out',
        ),
        migrations.AddField(
            model_name='attendance',
            name='afternoon_check_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='afternoon_check_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='morning_check_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='morning_check_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('Sick', 'Sick'), ('Vacation', 'Vacation'), ('Maternity', 'Maternity'), ('Paternity', 'Paternity'), ('Unpaid', 'Unpaid')], max_length=20),
        ),
    ]
