# Generated by Django 5.0.2 on 2024-06-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_employee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='afternoon_check_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='afternoon_check_out',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='morning_check_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='morning_check_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
