# Generated by Django 5.0.2 on 2024-06-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_employee_user_alter_attendance_afternoon_check_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='afternoon_check_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='afternoon_check_out',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='morning_check_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='morning_check_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
