# Generated by Django 5.0.2 on 2024-06-29 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_attendance_afternoon_check_in_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
