# Generated by Django 5.0.2 on 2024-07-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_departmenthead'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='employee_qr_codes/'),
        ),
    ]
