# Generated by Django 5.0.2 on 2024-07-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_employee_qr_code_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='afternoon_check_in',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='afternoon_check_out',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='morning_check_in',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='morning_check_out',
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
