# Generated by Django 5.0.2 on 2024-07-05 06:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_created_at_notification_timestamp_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DepartmentHead',
            new_name='UserForDepartmentHead',
        ),
    ]
