# Generated by Django 5.0.3 on 2024-09-23 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_leave_image_alter_leave_leave_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='budget',
        ),
    ]
